#!/bin/bash
#
# The "u2up-yocto" project build tool
#
# Copyright (C) 2017-2018 Samo Pogacnik <samo_pogacnik@t-2.net>
# All rights reserved.
#
# This file is part of the "u2up-yocto" software project.
# This file is provided under the terms of the BSD 3-Clause license,
# available in the LICENSE file of the "automk" software project.
#
#set -x
#set -e

function usage_help ()
{
	echo "Usage: "$(basename  $0)" [MACHINE COMMAND] [OPTIONS]"
	echo " MACHINE := qemux86|raspberrypi3-64"
	echo " COMMAND := prepare|build|bbsh"
	echo " OPTIONS := {--help|-h}"
	echo
	return
}

pre="$(basename  $0)-u2up: "
OPTIONS=""
COMMAND=""
MACHINE=""

DOWNLOADS="downloads"

POKY="poky"
POKY_BRANCH="thud"
POKY_REPO_URL="git://git.yoctoproject.org/poky"

while [[ $# > 0 ]]
do
	case $1 in
	qemux86|raspberrypi3-64)
		if [ -z "$COMMAND" ] && [ -z "$MACHINE" ]; then
			MACHINE=$1
			case $MACHINE in
			qemux86)
				BSP_LAYER_NAME=""
				MACH=""
				MACH_BRANCH=""
				MACH_REPO_URL=""
				;;
			raspberrypi3-64)
				BSP_LAYER_NAME="raspberrypi"
				MACH="meta-${BSP_LAYER_NAME}"
				MACH_BRANCH="${POKY_BRANCH}"
				MACH_REPO_URL="git://git.yoctoproject.org/${MACH}"
				;;
			esac
		else
			echo $pre"ERROR - Wrong syntax!"
			echo
			usage_help
			exit 1
		fi
		;;
	prepare|build|bbsh)
		if [ -n "$MACHINE" ] && [ -z "$COMMAND" ]; then
			COMMAND=$1
		else
			echo $pre"ERROR - Wrong syntax!"
			echo
			usage_help
			exit 1
		fi
		;;
	--help|-h)
		usage_help
		exit 0 
		;;
	*)
		echo $pre"ERROR - Unknown option: "$1
		echo
		usage_help
		exit 1
		;;
	esac
	shift # to the next token, if any
done

if [ -z "$COMMAND" ]; then
	echo $pre"ERROR - Missing COMMAND!"
	echo
	usage_help
	exit 1
fi

if [ -z "$MACHINE" ]; then
	echo $pre"ERROR - Missing MACHINE!"
	echo
	usage_help
	exit 1
fi

WDIR=$(dirname $0)
pushd $WDIR &> /dev/null

# Check downloads mirror!
function check_downloads ()
{
	if [ ! -d "$DOWNLOADS" ]; then
		return 1
	fi
	return 0
}

# Check subdir!
function check_subdir ()
{
	ret=1
	SUBTREE=$1
	BRANCH=$2

	# Check if no args (first arg empty) - dummy check; not an error:
	if [ -z "$SUBTREE" ]; then
		return 0
	fi

	# Chech second arg (if first arg exists, the second has to exist too):
	if [ -z "$BRANCH" ]; then
		echo $pre"ERROR - check_subdir () Invalid params!"
		return $ret
	fi

	if [ -d "${SUBTREE}_${BRANCH}" ]; then
		pushd ${SUBTREE}_${BRANCH} &> /dev/null
		git checkout $BRANCH &> /dev/null
		ret=$?
		popd &> /dev/null
		if [ $ret -ne 0 ]; then
			echo $pre"ERROR - check_subdir () Git branch test checkout error - Remove: ${SUBTREE}_${BRANCH}!"
			rm -rf ${SUBTREE}_$BRANCH
		else
			if [ ! -f "${DOWNLOADS}/${SUBTREE}_${BRANCH}_git.tar.gz" ]; then
				echo $pre"Archiving \"${SUBTREE}_${BRANCH}\" into \"${DOWNLOADS}/${SUBTREE}_${BRANCH}_git.tar.gz\"!"
				tar czf ${DOWNLOADS}/${SUBTREE}_${BRANCH}_git.tar.gz ${SUBTREE}_$BRANCH
				if [ $? -ne 0 ]; then
					echo $pre"WARNING - prepare failed (tar czf: ${SUBTREE}_${BRANCH} subdir not archived)!"
					echo
				fi
			fi
		fi
	fi
	return $ret 
}

# Prepare subdir!
function prepare_subdir ()
{
	ret=1
	SUBTREE=$1
	BRANCH=$2
	REPO_URL=$3

	# Check if no args (first arg empty) - dummy check; not an error:
	if [ -z "$SUBTREE" ]; then
		return 0
	fi

	if [ -z "$BRANCH" ] || [ -z "$REPO_URL" ]; then
		echo $pre"ERROR - check_subdir () Invalid params!"
		return $ret
	fi

	echo $pre"Preparing \"${SUBTREE}_${BRANCH}\" subdir (from \"$REPO_URL\")!"
	if [ ! -d "${SUBTREE}" ] && [ ! -d "${SUBTREE}_${BRANCH}" ]; then
		if [ -f "${DOWNLOADS}/${SUBTREE}_${BRANCH}_git.tar.gz" ]; then
			echo $pre"Extracting \"${SUBTREE}\" from \"${DOWNLOADS}/${SUBTREE}_${BRANCH}_git.tar.gz\"!"
			tar xzf ${DOWNLOADS}/${SUBTREE}_${BRANCH}_git.tar.gz
			ret=$?
			if [ $ret -ne 0 ]; then
				echo $pre"ERROR - prepare failed (tar xzf: ${SUBTREE}_${BRANCH} subdir not ok)!"
				echo
			fi
		else
			git clone --single-branch -b $BRANCH $REPO_URL ${SUBTREE}_$BRANCH
			ret=$?
			if [ $ret -ne 0 ]; then
				echo $pre"ERROR - prepare failed (git clone: ${SUBTREE}_${BRANCH} subdir not ok)!"
				echo
			else
				check_subdir $SUBTREE $BRANCH
				ret=$?
			fi
		fi
		if [ $ret -ne 0 ]; then
			rm -rf ${SUBTREE}_${BRANCH}
		fi
	else
		check_subdir $SUBTREE $BRANCH
		ret=$?
	fi
	return $ret
}

# Prepare tree for specific machine!
function prepare_machine ()
{
	ret=1

	check_downloads
	ret=$?
	if [ $ret -ne 0 ]; then
		echo $pre"Creating fresh \"${DOWNLOADS}\" directory!"
		mkdir -p $DOWNLOADS
	fi
	check_subdir $POKY $POKY_BRANCH
	ret=$?
	if [ $ret -ne 0 ]; then
		prepare_subdir $POKY $POKY_BRANCH $POKY_REPO_URL
		ret=$?
		if [ $ret -ne 0 ]; then
			echo $pre"ERROR - Failed!"
			echo
			return $ret
		fi
	fi
	check_subdir $MACH $MACH_BRANCH
	ret=$?
	if [ $ret -ne 0 ]; then
		prepare_subdir $MACH $MACH_BRANCH $MACH_REPO_URL
		ret=$?
	fi

	if [ $ret -eq 0 ]; then
		echo $pre"Done OK!"
	fi
	return $ret
}

# Build image for specific machine!
function build_machine ()
{
	ret=1

	check_downloads
	ret=$?
	if [ $ret -ne 0 ]; then
		echo $pre"ERROR - Project not yet prepared (downlads mirror not availabe)!"
		echo
		return $ret
	fi
	check_subdir $POKY $POKY_BRANCH
	ret=$?
	if [ $ret -ne 0 ]; then
		echo $pre"ERROR - Project not yet prepared (poky branch not availabe)!"
		echo
		return $ret
	fi
	check_subdir $MACH $MACH_BRANCH
	ret=$?
	if [ $ret -ne 0 ]; then
		echo $pre"ERROR - Project not yet prepared (machine branch not availabe)!"
		echo
		return $ret
	fi

	echo $pre"Setting build environment for \"${MACHINE}\"!"
	source ${POKY}_${POKY_BRANCH}/oe-init-build-env u2up_${POKY_BRANCH}/build.$MACHINE

	export YOCTO_BRANCH="${POKY_BRANCH}"
	export BB_ENV_EXTRAWHITE="$BB_ENV_EXTRAWHITE YOCTO_BRANCH"

	if [ -n "${1}" ] && [ "${1}" == "bbsh" ]; then
		echo $pre"Entering U2UP bitbake shell for \"${MACHINE}\"!"
		bash
	else
		echo $pre"Building U2UP image for \"${MACHINE}\"!"
		bitbake u2up-image-full-cmdline
	fi
	ret=$?
	if [ $ret -eq 0 ]; then
		echo $pre"Done OK!"
	fi
	return $ret
}

# Execute command!
ret=1
case $COMMAND in
prepare)
	prepare_machine
	ret=$?
	;;
build|bbsh)
	build_machine $COMMAND
	ret=$?
	;;
esac

exit $ret

